### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by Giorbertopazzosgravato** [nanovis/Shader-Editor#6]
when I try to `make serve` it gives me this error: 
``
em++  -Iinc -Ilib/glm  -Wall -Wformat -Os -s USE_WEBGPU=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=1 -s EXIT_RUNTIME=1 -s ASSERTIONS=0 -s FILESYSTEM=1 -s --use-preload-plugins -s USE_SDL=2 -s USE_LIBJPEG=1 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["bmp","png","jpg"]'  -c -o main.o main.cpp
make: em++: No such file or directory
make: *** [<builtin>: main.o] Error 127
``

**Comment by DonggangJia** [comment]
Could you try to move the texture folder to out/ or just create an empty out/texture folder?

**Comment by Giorbertopazzosgravato** [comment]
sorry for getting to you so late, I tried to move the texture folder to ```out/``` and rerun the project but it gives me the same error: 
```
em++  -Iinc -Ilib/glm  -Wall -Wformat -Os -s USE_WEBGPU=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=1 -s EXIT_RUNTIME=1 -s ASSERTIONS=0 -s FILESYSTEM=1 -s --use-preload-plugins -s USE_SDL=2 -s USE_LIBJPEG=1 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["bmp","png","jpg"]'  -c -o main.o main.cpp
make: em++: No such file or directory
make: *** [<builtin>: main.o] Error 127
```

**Comment by DonggangJia** [comment]
Please try the command `em++ -v` on your terminal. You might not have installed emscripten successfully or didn't set up the environment variables.
